# Don't change this! Version used to track needed updates.
version = 0
biomeColorRain = true

[biomes]
biomeParticlesRadius = 32
mushroomSporeBiomes = [
    "minecraft:mushroom_fields"
]
mushroomSporeDensity = 10
pollenBiomes = [
    "minecraft:flower_forest",
    "minecraft:sunflower_plains"
]
pollenDensity = 50
sculkDustBiomes = [
    "minecraft:deep_dark"
]
sculkDustDensity = 5

[geysers]
useUpdatedSmoke = false
flameGeyserSpawnChance = 5
flameGeyserSpawnableBlocks = [
    "minecraft:netherrack",
    "minecraft:blackstone",
    "minecraft:soul_soil"
]
flameGeyserSoundVolume = 0.5
flameGeyserActiveTime = 300
flameGeyserInactiveTime = 500
smokeGeyserSpawnChance = 5
smokeGeyserSpawnableBlocks = [
    "minecraft:netherrack",
    "minecraft:blackstone",
    "minecraft:soul_soil"
]
smokeGeyserSoundVolume = 0.2
smokeGeyserActiveTime = 300
smokeGeyserInactiveTime = 500
bubbleGeyserSpawnChance = 5
bubbleGeyserSpawnableBlocks = [
    "minecraft:sand",
    "minecraft:red_sand",
    "minecraft:gravel",
    "minecraft:dirt",
    "minecraft:clay"
]
bubbleGeyserSoundVolume = 0.5
bubbleGeyserActiveTime = 300
bubbleGeyserInactiveTime = 500

[fireflies]
firefliesEnabled = true
dimensionBlocklist = [
    "twilightforest:twilight_forest_type"
]
biomesBlocklist = [  ]
biomesAllowlist = [
    "minecraft:lush_caves"
]
spawnableBlocks = [
    "minecraft:grass",
    "minecraft:tall_grass",
    "minecraft:poppy",
    "minecraft:dandelion",
    "minecraft:peony",
    "minecraft:blue_orchid",
    "minecraft:allium",
    "minecraft:azure_bluet",
    "minecraft:orange_tulip",
    "minecraft:pink_tulip",
    "minecraft:red_tulip",
    "minecraft:white_tulip",
    "minecraft:oxeye_daisy",
    "minecraft:cornflower",
    "minecraft:lily_of_the_valley",
    "minecraft:sunflower",
    "minecraft:lilac",
    "minecraft:rose_bush",
    "minecraft:pink_petals",
    "minecraft:flowering_azalea"
]
defaultDensity = 3
ignoredSeasons = "DEFAULT"
fireflyType = "ORIGINAL"
fireflySoundVolume = 1.0
onlyAllowInHabitatBiomes = true
habitatBiomes = [
    "minecraft:swamp",
    "minecraft:mangrove_swamp"
]
habitatBiomeDensity = 3

[waterfalls]
waterfallsEnabled = true
smallWaterfallsEnabled = true
waterfallUpdateFrequency = 6
randomizeWaterfallParticleRotation = false
mediumWaterfallParticleDensity = 1.0
mediumWaterfallHeightThreshold = 6
forceSpawnMediumWaterfallParticles = true
largeWaterfallsEnabled = true
largeWaterfallParticleDensity = 1.0
largeWaterfallHeightThreshold = 10
forceSpawnLargeWaterfallParticles = true