# Don't change this! Version used to track needed updates.
version = 0
enableParticleCulling = true
particleRenderDistance = 24
particleCullingBlocklist = [  ]
cullParticlesInUnloadedChunks = true
allowUsingBlendedRenderType = true
spellParticlesUseBlendedRenderType = true
glowingLavaDrops = true
fluidDropsEvaporate = true
fluidDropsEvaporationVolume = 0.25
dropLandInFluidRipples = true
dropLandSoundVolume = 1.0
lavaSparkSmoke = true
sparksScale = 1.0
poppingHearts = true
poppingBubbles = true
poppingBubblesVolume = 0.2
glowingEnchantmentParticles = true
translucentEnchantmentParticles = true
disableRandomizedShading = true
potionParticleAlpha = 0.7
potionParticleAlphaNearPlayer = 0.2
leavesLandOnGround = true
leavesLandOnWater = true
leavesLandingOnWaterRipples = true
leavesLandingOnWaterKeepMomentum = true
fallenLeavesLifeTime = 40
rainIncreasesLeavesMovementSpeed = true
fireOverlayHeight = -0.15
fireOverlayAlpha = 0.9
fireOverlayAlphaWithFireResistance = 0.4
mobSkullShaders = true
nightVisionFading = true
nightVisionFadingTime = 100
enableEasterEggs = false