
[Difficulty]
	#Overrides all other config options for easy difficulty management
	#This value is changed by the in-game config. It does nothing otherwise.
	#Range: 0 ~ 4
	Difficulty = 4
	#Defines the minimum habitable temperature
	#Range: -Infinity ~ Infinity
	"Minimum Habitable Temperature" = 0.08571428571551021
	#Defines the maximum habitable temperature
	#Range: -Infinity ~ Infinity
	"Maximum Habitable Temperature" = 1.619047619047619
	#Rate at which the player's body temperature changes (default: 1.0 (100%))
	#Range: 0.0 ~ Infinity
	"Rate Multiplier" = 0.75
	#Damage dealt to the player when they are too hot or too cold
	#Range: 0.0 ~ Infinity
	"Temperature Damage" = 1.0
	#Sets whether damage scales with difficulty
	"Damage Scaling" = true

[Items]
	#Allow fire resistance to block overheating damage
	"Fire Resistance Immunity" = true
	#Allow ice resistance to block freezing damage
	"Ice Resistance Immunity" = true
	#Thermometer item is required to see detailed world temperature
	"Require Thermometer" = true

["Temperature Effects"]

	["Temperature Effects".Hot]
		#When set to true, the player's view distance will decrease when they are too hot
		"Heatstroke Fog" = true

	["Temperature Effects".Cold]
		#When set to true, some of the player's hearts will freeze when they are too cold, preventing regeneration
		"Freezing Hearts" = true
		#When set to true, the player's attack knockback will be reduced when they are too cold
		"Cold Knockback Reduction" = true
		#When set to true, the player's movement speed will be reduced when they are too cold
		"Cold Slowness" = true
		#When set to true, the player's mining speed will be reduced when they are too cold
		"Cold Mining Fatigue" = true

["Grace Period"]
	#The number of ticks after the player spawns during which they are immune to temperature effects
	#Range: > 0
	"Grace Period Length" = 6000
	#Enables the grace period
	"Grace Period Enabled" = true

