
#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_end", -0.1, "MC"], ["minecraft:the_nether", 0.7, "MC"]]
	#Overrides existing dimension temperatures & offsets
	#Also overrides temperatures of all biomes in the dimension
	"Dimension Temperatures" = []

#Format: [["biome_1", tempLow, tempHigh, *units], ["biome_2", tempLow, tempHigh, *units]... etc]
#temp-low: The temperature of the biome at midnight
#temp-high: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding existing biome temperatures & offsets.
	"Biome Temperatures" = [["terralith:amethyst_rainforest", 69.0, 84.0, "F"], ["terralith:alpine_grove", 16.0, 53.0, "F"], ["terralith:volcanic_crater", 96.0, 162.0, "F"], ["minecraft:savanna_plateau", 76.0, 98.0, "F"], ["terralith:arid_highlands", 74.0, 102.0, "F"], ["minecraft:taiga", 44.0, 62.0, "F"], ["terralith:cloud_forest", 38.0, 58.0, "F"], ["minecraft:savanna", 70.0, 95.0, "F"], ["terralith:shield_clearing", 28.0, 80.0, "F"], ["minecraft:swamp", 72.0, 84.0, "F"], ["terralith:brushland", 64.0, 89.0, "F"], ["minecraft:frozen_peaks", 15.0, 33.0, "F"], ["terralith:warped_mesa", 66.0, 84.0, "F"], ["minecraft:old_growth_spruce_taiga", 48.0, 62.0, "F"], ["minecraft:deep_dark", 63.0, 63.0, "F"], ["terralith:red_oasis", 58.0, 94.0, "F"], ["terralith:bryce_canyon", 72.0, 110.0, "F"], ["minecraft:warm_ocean", 67.0, 76.0, "F"], ["terralith:blooming_plateau", 49.0, 78.0, "F"], ["terralith:haze_mountain", 62.0, 74.0, "F"], ["minecraft:windswept_forest", 48.0, 66.0, "F"], ["terralith:lavender_forest", 56.0, 75.0, "F"], ["minecraft:stony_shore", 50.0, 64.0, "F"], ["terralith:steppe", 44.0, 78.0, "F"], ["terralith:birch_taiga", 40.0, 62.0, "F"], ["terralith:shield", 48.0, 68.0, "F"], ["minecraft:old_growth_birch_forest", 58.0, 72.0, "F"], ["minecraft:desert", 48.0, 115.0, "F"], ["terralith:desert_canyon", 73.0, 121.0, "F"], ["minecraft:snowy_taiga", 19.0, 48.0, "F"], ["minecraft:deep_frozen_ocean", 56.0, 65.0, "F"], ["minecraft:river", 60.0, 70.0, "F"], ["minecraft:old_growth_pine_taiga", 48.0, 62.0, "F"], ["terralith:rocky_mountains", 45.0, 73.0, "F"], ["minecraft:eroded_badlands", 88.0, 120.0, "F"], ["terralith:volcanic_peaks", 76.0, 122.0, "F"], ["terralith:yellowstone", 47.0, 68.0, "F"], ["minecraft:bamboo_jungle", 76.0, 87.0, "F"], ["terralith:lavender_valley", 59.0, 76.0, "F"], ["minecraft:snowy_beach", 38.0, 52.0, "F"], ["terralith:sandstone_valley", 78.0, 114.0, "F"], ["terralith:moonlight_valley", 57.0, 76.0, "F"], ["terralith:orchid_swamp", 62.0, 81.0, "F"], ["minecraft:jungle", 76.0, 87.0, "F"], ["minecraft:snowy_slopes", 24.0, 38.0, "F"], ["terralith:temperate_highlands", 54.0, 80.0, "F"], ["terralith:granite_cliffs", 65.0, 85.0, "F"], ["minecraft:soul_sand_valley", 53.0, 53.0, "F"], ["terralith:caldera", 58.0, 71.0, "F"], ["minecraft:badlands", 84.0, 120.0, "F"], ["terralith:basalt_cliffs", 76.0, 122.0, "F"], ["terralith:savanna_badlands", 68.0, 99.0, "F"], ["terralith:fractured_savanna", 65.0, 92.0, "F"], ["terralith:forested_highlands", 43.0, 70.0, "F"], ["minecraft:wooded_badlands", 80.0, 108.0, "F"], ["terralith:highlands", 62.0, 74.0, "F"], ["minecraft:windswept_savanna", 67.0, 90.0, "F"], ["terralith:ancient_sands", 83.0, 130.0, "F"], ["terralith:desert_spires", 60.0, 121.0, "F"]]

["Block Temperature"]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range (max 7)>, <*true/false: falloff>, <*max effect>, <*predicates>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:
	#block-ids: multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: the temperature of the block, in Minecraft units
	#falloff: the block is less effective as distance increases
	#max effect: the maximum temperature change this block can cause to a player (even with multiple blocks)
	#predicates: the state that the block has to be in for the temperature to be applied (lit=true for a campfire, for example).
	#Multiple predicates can be used by separating them with commas (i.e: "lit=true,waterlogged=false")
	BlockTemps = [["minecraft:soul_fire", -0.476, 7, true, 0.8], ["minecraft:fire", 0.476, 7, true, 0.8], ["minecraft:magma_block", 0.5, 3, true, 0.6], ["minecraft:soul_campfire", -0.476, 3, true, 0.6, "lit=true"], ["minecraft:ice", -0.15, 4, true, 0.5], ["minecraft:packed_ice", -0.25, 4, true, 1.0], ["minecraft:blue_ice", -0.35, 4, true, 1.0]]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7

[Misc]
	#The amount of temperature normalization from being deep underground
	#0.0 = no insulation, 1.0 = full insulation
	#Range: 0.0 ~ 1.0
	"Cave Insulation Strength" = 1.0

[Hearth]
	#How strong the hearth is
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.75
	#List of additional blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = ["minecraft:iron_bars", "minecraft:jungle_leaves", "minecraft:oak_leaves", "minecraft:spruce_leaves", "minecraft:dark_oak_leaves", "minecraft:acacia_leaves", "minecraft:birch_leaves", "minecraft:azalea_leaves", "minecraft:flowering_azalea_leaves", "minecraft:mangrove_leaves", "minecraft:cherry_leaves", "blue_skies:bluebright_leaves", "blue_skies:starlit_leaves", "blue_skies:frostbright_leaves", "blue_skies:lunar_leaves", "blue_skies:dusk_leaves", "blue_skies:maple_leaves", "blue_skies:crystallized_leaves", "blue_skies:comet_leaves", "blue_skies:crescent_fruit_leaves", "undergarden:smogstem_leaves", "undergarden:wigglewood_leaves", "undergarden:grongle_leaves", "create:encased_fluid_pipe"]
	#List of additional blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []

