
#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_end", -0.1, "MC"], ["minecraft:the_nether", 0.7, "MC"]]
	#Overrides existing dimension temperatures & offsets
	#Also overrides temperatures of all biomes in the dimension
	"Dimension Temperatures" = []

#Format: [["biome_1", tempLow, tempHigh, *units], ["biome_2", tempLow, tempHigh, *units]... etc]
#temp-low: The temperature of the biome at midnight
#temp-high: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding existing biome temperatures & offsets.
	"Biome Temperatures" = []

[Misc]
	#The amount of temperature normalization from being deep underground
	#0.0 = no insulation, 1.0 = full insulation
	#Range: 0.0 ~ 1.0
	"Cave Insulation Strength" = 1.0
	#Overrides the world temperature when the player is within this structure
	#Format: [["structure_1", temperature1, *units], ["structure_2", temperature2, *units]... etc]
	#(* = optional)
	"Structure Temperatures" = [["minecraft:igloo", 65.0, "F"]]
	#Offsets the world temperature when the player is within this structure
	#Format: [["structure_1", offset1, *units], ["structure_2", offset2, *units]... etc]
	#(* = optional)
	"Structure Temperature Offsets" = []
	#List of blocks that will allow the player to sleep on them, regardless of the "Prevent Sleep When in Danger" setting
	#Use this list if the player is not getting the temperature effect from sleeping on particular blocks
	"Sleep Check Override Blocks" = ["#comforts:sleeping_bags"]
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Check Sleeping Conditions" = true
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

[Hearth]
	#How effective the hearth is at normalizing temperature
	#Range: 0.0 ~ 1.0
	"Hearth Strength" = 0.75
	#List of additional blocks that the hearth can spread through
	#Use this list if the hearth isn't spreading through particular blocks that it should
	"Hearth Spread Whitelist" = ["minecraft:iron_bars", "minecraft:jungle_leaves", "minecraft:oak_leaves", "minecraft:spruce_leaves", "minecraft:dark_oak_leaves", "minecraft:acacia_leaves", "minecraft:birch_leaves", "minecraft:azalea_leaves", "minecraft:flowering_azalea_leaves", "minecraft:mangrove_leaves", "minecraft:cherry_leaves", "blue_skies:bluebright_leaves", "blue_skies:starlit_leaves", "blue_skies:frostbright_leaves", "blue_skies:lunar_leaves", "blue_skies:dusk_leaves", "blue_skies:maple_leaves", "blue_skies:crystallized_leaves", "blue_skies:comet_leaves", "blue_skies:crescent_fruit_leaves", "undergarden:smogstem_leaves", "undergarden:wigglewood_leaves", "undergarden:grongle_leaves", "create:encased_fluid_pipe"]
	#List of additional blocks that the hearth cannot spread through
	#Use this list if the hearth is spreading through particular blocks that it shouldn't
	"Hearth Spread Blacklist" = []

[Blocks]
	#Allows for adding simple BlockTemps without the use of Java mods
	#Format (All temperatures are in Minecraft units):
	#[["block-ids", <temperature>, <range (max 7)>, <*true/false: falloff>, <*max effect>, <*predicates>], [etc...], [etc...]]
	#(* = optional) (1 °MC = 42 °F/ 23.33 °C)
	#
	#Arguments:
	#block-ids: multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	#temperature: the temperature of the block, in Minecraft units
	#falloff: the block is less effective as distance increases
	#max effect: the maximum temperature change this block can cause to a player (even with multiple blocks)
	#predicates: the state that the block has to be in for the temperature to be applied (lit=true for a campfire, for example).
	#Multiple predicates can be used by separating them with commas (i.e: "lit=true,waterlogged=false")
	"Block Temperatures" = [["minecraft:soul_fire,create_connected:fan_haunting_catalyst,create_connected:fan_freezing_catalyst,blue_skies:snowcap_oven,endersdelight:endstone_stove,decorative_blocks:soul_chandelier,decorative_blocks:soul_brazier,supplementaries:sconce_soul", -0.476, 7, true, 1.0], ["minecraft:fire,create_connected:fan_smoking_catalyst,create:blaze_burner,blue_skies:horizonite_forge,farmersdelight:stove,nethersdelight:blackstone_stove,decorative_blocks:chandelier,decorative_blocks:brazier,supplementaries:sconce_lever,supplementaries:sconce", 0.476, 7, true, 1.0], ["minecraft:magma_block,botania:blaze_block", 0.5, 3, true, 0.7], ["minecraft:torch,undergarden:shard_torch,tide:jelly_torch,minecraft:lantern,suppsquared:copper_lantern,undergarden:cloggrum_lantern,suppsquared:crimson_lantern,minecraft:jack_o_lantern,immersiveengineering:lantern,undergarden:gloom_o_lantern,undergarden:shard_o_lantern,salt:salt_lamp", 0.35, 5, true, 1.2], ["minecraft:soul_torch,minecraft:soul_lantern,blue_skies:moonstone_lantern", -0.35, 5, true, 1.2], ["minecraft:soul_campfire", -0.476, 7, true, 0.6, "lit=true"], ["minecraft:ice", -0.15, 4, true, 0.5], ["minecraft:packed_ice", -0.25, 4, true, 1.0], ["minecraft:blue_ice", -0.35, 4, true, 1.0], ["minecraft:lava_cauldron,create_connected:fan_blasting_catalyst", 0.5, 7, true, 1.5]]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7

