
["Server Configs"]
	#Maximum width of Oil Barrels
	"Max Oil Barrel Width" = 3
	#Canister Capacity in mB
	"Capacity of Canisters" = 4000
	#Canister Capacity Enchantment Capacity Addition in mB
	"Capacity Addition of Capacity Enchantment in Canisters" = 1000
	#Canister can be filled by spouts
	"Canister can be filled by spouts" = true
	#Combustibles do boom boom when on fire
	"Combustibles blow up" = true
	#Asphalt Degradation Speed Multiplier
	#Range: 0.0 ~ 1.7976931348623157E308
	"Asphalt Degradation Speed Multiplier" = 10.0

	["Server Configs"."Diesel Engines"]
		#Turbocharged Diesel Engine Speed Multiplier
		"Turbocharged Diesel Engine Speed Multiplier" = 2.0
		#Turbocharged Diesel Engine Burn Rate Multiplier
		"Turbocharged Diesel Engine Burn Rate Multiplier" = 1.0
		#Whenever Normal Diesel Engines are enabled
		"Normal Diesel Engines" = true
		#Whenever Modular Diesel Engines are enabled
		"Modular Diesel Engines" = true
		#Whenever Huge Diesel Engines are enabled
		"Huge Diesel Engines" = true
		#Whenever Diesel Engines can be filled with an Item
		"Engines filled with a bucket" = false
		#Whenever Diesel Engines can be disabled with redstone
		"Engines disabled with redstone" = true

	["Server Configs"."Oil Config"]
		#Normal oil chunks oil amount multiplier
		"Normal oil chunks oil amount multiplier" = 1.0
		#High oil chunks oil amount multiplier
		"High oil chunks oil amount multiplier" = 1.0
		#Max Oil Scanner Level
		"Max Oil Scanner Level" = 10000
		#Normal oil chunks percentage
		#Range: 0.0 ~ 100.0
		"Normal oil chunks percentage" = 10.0
		#High oil chunks percentage
		#Range: 0.0 ~ 100.0
		"High oil chunks percentage" = 10.0
		#Oil deposits bigger than this value are infinite
		"Infinite oil deposits from" = 10000

