
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1022312
	#The name of the modpack
	modpackName = "Path of Truth"
	#The version of the modpack
	modpackVersion = "V2.4"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

