
["Chicken Nerf"]
	#Minimum count of eggs produced by chickens after mating
	#Range: 0 ~ 64
	laid_eggs_count_minimum = 1
	#The amount by which the maximum count of eggs laid exceeds the minimum number of eggs laid
	#Range: 0 ~ 64
	laid_eggs_count_variation = 2
	#Probability of an egg successfully hatching a chick
	#Range: 0.0 ~ 1.0
	chicken_hatching_probability = 0.6

