
#Enabled items
[Items]
	adzuki_gummy = true
	aloe_gummy = true
	apple_gummy = true
	baked_portobello_cap = true
	banana_gummy = true
	beetroot_gummy = true
	berry_limeade = true
	big_rice_ball = true
	black_tea_gummy = true
	buttered_legs = true
	candied_lime = true
	chieftain_claw = true
	chieftain_crab = true
	chieftain_crab_bucket = true
	chieftain_crab_meat = true
	chieftain_crab_spawn_egg = true
	chieftain_leg = true
	chiseled_urchin_test_bricks = true
	chocolate_arils = true
	chocolate_gummy = true
	clam = true
	clam_bucket = true
	clam_chowder = true
	clam_meat = true
	clam_meatball_stew = true
	clam_pasta = true
	clam_roll = true
	clam_spawn_egg = true
	cod_ceviche = true
	coffee_gummy = true
	cooked_platinum_bass = true
	cooked_platinum_bass_head = true
	cooked_platinum_bass_slice = true
	cooked_tiger_prawn = true
	crab_lasagna = true
	crab_miso = true
	crab_noodles = true
	crimson_carrot_roast = true
	deluxe_salad = true
	fish_mix = true
	glazed_strider = true
	glow_berry_gummy = true
	green_tea_gummy = true
	honey_lime_chicken = true
	land_and_sea_burger = true
	lime = true
	lime_cake = true
	lime_cake_slice = true
	lime_cookie = true
	lime_crate = true
	lime_green_tea = true
	lime_gummy = true
	lime_ice_cream = true
	lime_ice_cream_block = true
	lime_milkshake = true
	lime_pie = true
	lime_pie_slice = true
	lime_popsicle = true
	lime_seeds = true
	lime_slice = true
	limeade = true
	lunar_pearl = true
	mediterranean_salmon = true
	melon_gummy = true
	mint_gummy = true
	mint_limeade = true
	passion_fruit_gummy = true
	pink_limeade = true
	platinum_bass = true
	platinum_bass_bucket = true
	platinum_bass_head = true
	platinum_bass_slice = true
	platinum_bass_spawn_egg = true
	platinum_bass_stew = true
	pomegranate = true
	pomegranate_bean_salad = true
	pomegranate_black_tea = true
	pomegranate_cake = true
	pomegranate_cake_slice = true
	pomegranate_chicken = true
	pomegranate_crate = true
	pomegranate_custard = true
	pomegranate_gummy = true
	pomegranate_ice_cream = true
	pomegranate_ice_cream_block = true
	pomegranate_milkshake = true
	pomegranate_mutton = true
	pomegranate_pork = true
	pomegranate_seeds = true
	pomegranate_slice = true
	pomegranate_smoothie = true
	portobello = true
	portobello_burger = true
	portobello_colony = true
	portobello_pasta = true
	portobello_quiche = true
	portobello_quiche_slice = true
	portobello_rice_soup = true
	portobello_risotto = true
	portobello_wrap = true
	potato_fritters = true
	prawn_ceviche = true
	prawn_noodles = true
	prawn_po_boy = true
	prawn_roll = true
	prawn_stew = true
	pumpkin_gummy = true
	salmon_tartare = true
	salmon_wrapped_prawn = true
	sea_wrap = true
	spicy_grenadine_jelly = true
	strawberry_gummy = true
	strawberry_jam_bun = true
	stuffed_portobello_cap = true
	sweet_berry_gummy = true
	tiger_prawn = true
	tiger_prawn_bucket = true
	tiger_prawn_spawn_egg = true
	uni = true
	uni_roll = true
	urchin = true
	urchin_bucket = true
	urchin_needle = true
	urchin_spawn_egg = true
	urchin_test = true
	urchin_test_block = true
	urchin_test_brick_slab = true
	urchin_test_brick_stairs = true
	urchin_test_brick_wall = true
	urchin_test_bricks = true
	urchin_test_tile_slab = true
	urchin_test_tile_stairs = true
	urchin_test_tile_wall = true
	urchin_test_tiles = true
	vanilla_gummy = true
	yellow_tea_gummy = true
	yucca_gummy = true
	pearly_claw = true
	shimmering_apple = true
	shimmering_pearl = true
	stygian_pomegranate = true
	urchin_dart = true

[Behavior]
	#Whether Lime Bushes require Bee pollination to reach final growth stage.
	lime_pollination = false
	#Whether Pomegranate Bushes require Bee pollination to reach final growth stage in the Overworld.
	pomegranate_pollination = false
	#Whether bee pollination of bushes should occur much quicker (when Bee collides with it) rather than on Bee's AI scheduled timing. Use this if having issues with pollination.
	fast_pollinate = false

