
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.cake]

		[types.cake.blue_skies]
			comet_berry_pie = true

		[types.cake.collectorsreap]
			lime_cake = true
			pomegranate_cake = true

	[types.wood_type]

		[types.wood_type.blue_skies]
			crystallized = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.outer_end]
			azure = true

		[types.wood_type.betterarcheology]
			rotten = true

	[types.leaves_type]

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = true
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			snowblossom = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.blue_skies]
			crystallized = true
			crescent_fruit = true
			bluebright = true
			starlit = true
			frostbright = true
			lunar = true
			dusk = true
			maple = true
			comet = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.outer_end]
			azure = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			trim = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.vct]
			crafting_table = true

		[entries.wood_type.beautify]
			trellis = true
			blinds = true
			picture_frame = true

