
#Gutter Outlet settings
[gutter_outlet]
	#Whether gutter outlet can collect rain water
	collectRain = true
	#Whether gutter outlet can collect snow as powder snow fluid
	collectSnow = true
	#Whether gutter outlet can collect fluid from dripstone (lava/water)
	collectDripstone = true
	#Whether gutter outlet can collect world fluid sources from above
	collectWorldFluid = true

	#Copper Sink settings
	[gutter_outlet.copper_sink]
		#Whether the Copper Sink provides infinite water (if false, it's just a normal 2000mB tank)
		infiniteWater = false

