
["food effects tooltip"]
	#Show suspicious stew food effects tooltips
	showSuspiciousStewTooltips = false
	#Use Lists as Whitelists instead.
	whitelistInstead = false
	#Blacklisted Item.
	blacklistItems = ["modid:testitem"]
	#Blacklisted Mod IDs.
	blacklistModsIDs = ["modid"]

