
["Render Radius"]
	#displayFeedbackButtonOnPauseScreen
	displayFeedbackButtonOnPauseScreen = true
	#displayFeedbackButtonOnInventoryScreen
	displayFeedbackButtonOnInventoryScreen = true
	#displayFeedbackButtonOnDeathScreen
	displayFeedbackButtonOnDeathScreen = true

