#The time in ticks in which a player can still be rescued from death. 20 ticks are one second. Set to 0 to disable the timer.
#Range: > -2147483648
ticksUntilDeath = 2400
#If true, the timer until death continues even if the player logs out.
continueTimerWhileOffline = false
#The time in ticks it takes to rescue a player. 20 ticks are one second.
#Range: > -2147483648
rescueActionTicks = 40
#The amount of health to respawn with when a player was rescued, out of 20.
#Range: > -2147483648
rescueRespawnHealth = 1
#The food level to respawn with when a player was rescued, out of 20.
#Range: > -2147483648
rescueRespawnFoodLevel = 5
#Effects applied to a player when rescued, in the format "effect|duration|amplifier"
rescueRespawnEffects = ["minecraft:hunger|600|0", "minecraft:weakness|1200|0"]
#The distance at which a player can rescue another.
#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
rescueDistance = 5.0
#If true, knocked out players will glow, making them visible through blocks.
glowOnKnockout = true
#If true, knocked out players are still able to punch nearby enemies.
allowUnarmedMelee = false
#If true, knocked out players are still able to fire bows.
allowBows = false
#If true, knocked out players are still able to fire pistols from Mr Crayfish's Gun Mod.
allowPistols = false

