
[general]
	leaves_decay_particles = true
	falling_leaf_particles = true
	decay_sound = true
	#Range: 0.0 ~ 1.0
	falling_leaf_rate = 0.07999999821186066
	#Range: 0.0 ~ 1.0
	rainy_falling_leaf_rate = 0.20000000298023224
	#Range: 0.0 ~ 1.0
	stormy_falling_leaf_rate = 0.4000000059604645

