
[general]
	block_growths = true
	#put here the name of a block growth json you want to disable i.e: [weeds, weeds_spread].Note that this is not the preferred way to do this as block growths are all data driven so it would be best to disable or tweak them by creating a datapack that overrides themCheck the mod data folder for the required names. Requires resource reload (/data reload)
	block_growth_blacklist = []
	creative_tab = false
	#Drop stuff when in creative
	drop_in_creative = false
	#Save generated resources to disk in a 'debug' folder in your game directory. Mainly for debug purposes but can be used to generate assets in all wood types for your mods :0
	debug_save_dynamic_pack = false

[mossy_blocks]
	#Range: 0.0 ~ 1.0
	interest_for_face = 0.3
	#Range: 0.0 ~ 1.0
	patchiness = 0.5
	#Range: 0.0 ~ 1.0
	immune_chance = 0.4
	needs_air = true
	enabled = true

[cracked_blocks]
	cracking_drops_brick = false
	#Range: 0.0 ~ 1.0
	interest_for_face = 0.6
	#Range: 0.0 ~ 1.0
	patchiness = 0.4
	#Range: 0.0 ~ 1.0
	immune_chance = 0.4
	needs_air = false
	enabled = true

[icicle]
	react_to_vibrations = true
	#Range: 1 ~ 100
	spawn_rarity = 12
	disable_icicles = false

[freezing]
	#Range: 0 ~ 1000
	icicle = 300

[charring]
	#Range: 0.0 ~ 1.0
	fire_chars_wood = 0.3
	soot_spawn = true
	flammable_cobweb = true

[item_interaction]
	pickaxe_cracking = true
	pickaxe_cracking_shift = false
	brick_breaking = true
	azalea_shearing = true
	moss_shearing = true
	moss_burning = true
	shovel_extinguish = true
	sponge_rusting = true
	sponge_rust_drying = false
	axe_stripping = true
	axe_rusting = true

[food]
	icicle_food = true
	icicle_fire_resistance = true

[misc]
	composter_dirt = true
	grass_over_mycelium = true
	mycelium_over_grass = true
	generic_bark = ""
	leggings_prevents_thorn_damage = true

[leaf_piles]
	leaf_piles_slow = true
	#Range: 0.0 ~ 1.0
	spawn_entity_from_decay = 0.3
	#Range: 1 ~ 256
	reach = 12
	#Range: 1 ~ 8
	max_pile_height = 3
	#leaves that wont spawn leaf piles
	leaf_piles_blacklist = []

[thin_ice]
	natural_melting = false

[lightning_growths]
	vitrified_lightning = true
	#chance that a lightning strike on sand creates fulgurite
	#Range: 0.0 ~ 1.0
	fulgurite_chance = 0.4

[rusting]
	rusting = true
	#Range: 1 ~ 8
	rusting_influence_radius = 4
	#Range: 0.0 ~ 1.0
	rusting_rate = 0.06
	rust_streaking = true

