
["Ice Aspect"]
	#Determines the amount of extra damage that Ice Aspect should do every second
	"Ice damage" = 1.0
	#Determines the amount of ticks (1/20 of a second) for which Ice Aspect should freeze every level (this number x 1 + 0.5 per level)
	"Ice seconds" = 60.0
	#Should Ice Aspect exist?
	"Allow Ice Aspect" = true
	#Should Ice Aspect be incompatible with Poison Aspect?
	"Incompatible with Poison Aspect" = true
	#Should Ice Aspect be incompatible with Fire Aspect?
	"Incompatible with Fire Aspect" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

[Lightness]
	#Determines the amount of attack speed that each level of Lightness should add
	"Lightness Amount" = 0.1
	#Should Lightness exist?
	"Allow Lightness" = true
	#Should Lightness be incompatible with Reach?
	"Incompatible with Reach" = true
	#Should Lightness be incompatible with Sweeping Edge?
	"Incompatible with Sweeping Edge" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

[Reach]
	#Determines the amount of Attack Reach that each level of Reach adds
	"Reach Amount" = 0.33
	#Should Reach exist?
	"Allow Reach" = true
	#Should Reach be incompatible with Sweeping Edge?
	"Incompatible with Sweeping Edge" = true
	#Should Reach be incompatible with Lightness
	"Incompatible with Lightness" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

[Floating]
	#Determines the amount of weight taken each level while elytra-flying with Floating
	"Float amount" = 0.01
	#Should Floating exist?
	"Allow Floating" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

[Bait]
	#Determines the percentage per level of finding extra loot with Bait
	"Bait Chance" = 15.0
	#Determines the maximum amount of loot items that should be given with Bait
	"Maximum Bait Loot" = 1.0
	#Determines whether Bait should only give fish
	"Only Fish" = false
	#Should Bait exist?
	"Allow Bait" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

[Blocking]
	#Determines the percentage of chance per level to block damage
	"Block Chance" = 5.0
	#Should Blocking exist?
	"Allow Blocking" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = false

[Boosting]
	#Determines the amount of XP per level addedd upon killing an entity while using Boosting
	"Extra XP" = 1.5
	#Should Boosting exist?
	"Allow Boosting" = true
	#Should Boosting be incompatible with Looting?
	"Incompatible with Looting" = true
	#Should Boosting be incompatible with Blood Blade?
	"Incompatible with Blood Blade" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

["Lava Walker"]
	#Should Lava Walker exist?
	"Allow Lava Walker" = true
	#Should Lava Walker be incompatible with Frost Walker?
	"Incompatible with Frost Walker" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = false

[Spikes]
	#Determines the amount of damage per level the attackers take upon hitting the shield
	"Spike Damage" = 1.0
	#Should Spikes exist?
	"Allow Spikes" = true
	#Should Spikes be incompatible with Reflection?
	"Incompatible with Reflection" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

[Reflection]
	#Determines the amount of base damage the reflected projectile should do. This is a modifier, so it will be multiplicated by the amount of damage the incoming projectile does, giving the final amount 
	"Base Reflected damage" = 0.3
	#Determines the amount added to the previous number for each Reflection level
	"Reflected damage increase per level" = 0.15
	#Determines the speed modifier for the reflected projectile
	"Speed modifier Base" = 0.9
	#Determines the speed increase each level of Reflection should give to the previous number
	"Speed modifier increase per level" = 0.3
	#Should Reflection exist?
	"Allow Reflection" = true
	#Should Reflection be incompatible with Spikes?
	"Incompatible with Spikes" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true
	#Determines whether Reflection should also work on tridents (Might cause some lag)
	"Reflect Tridents" = false

[Acceleration]
	#Determines the initial divider of the distance to determine the increased damage of Acceleration. This number will be decreased based on the level
	"Initial Distance Divider" = 9.5
	#Determines the max damage amount that can be dealt with a single accelerated shot. This number will be increased based on the level
	"Initial Damage cap" = 5.5
	#Determines by how much the Initial Distance Divider and the Initial Damage cap will be increased/decreased per level of Acceleration
	"Level changer" = 0.5
	#Should Acceleration exist?
	"Allow Acceleration" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

[Enhancement]
	#Determines the modifier per level for the XP to get when breaking blocks with Enhancement
	"XP modifier" = 0.25
	#Determines the chance per level to obtain extra XP  when mining blocks that don't give any XP while using Enhancement
	"Enhancement Chance" = 0.15
	#Should Enhancement exist?
	"Allow Enhancement" = true
	#Should Enhancement be incompatible with Fortune?
	"Incompatible with Fortune" = true
	#Should Enhancement be incompatible with Auto-Smelting?
	"Incompatible with Auto-Smelting" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

[Length]
	#Determines the amount of interaction reach increased by Length each level
	"Length addition" = 0.5
	#Should Length exist?
	"Allow Length" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

["Blaze Guard"]
	#Determines the duration of the fire applied for each level of Blaze Guard
	"Fire Duration" = 1.0
	#Should Blaze Guard exist?
	"Allow Blaze Guard" = true
	#Should Blaze Guard be incompatible with Chill Guard?
	"Incompatible with Chill Guard" = true
	#Should Blaze Guard be incompatible with Shove
	"Incompatible with Shove" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

[Soaring]
	#Determines whether there should be a check to see if the elytra wearer isn't looking upwards to increase velocity. Disabling this makes fireworks unnecessary to keep flying with Soaring
	"Check Head Pitch" = true
	#Determines the maximum velocity after which Soaring will stop increasing the speed
	"Max Velocity" = 1.2
	#Determines by how much Soaring should increase the speed each second per level
	"Speed increase" = 0.06
	#Should Soaring exist?
	"Allow Soaring" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = false

["Chill Guard"]
	#Determines the amount of seconds each level of Chill Guard should freeze for
	"Chill Seconds" = 3.0
	#Determines the amount of freeze damage that Chill Guard should deal
	"Chill damage" = 1.0
	#Should Chill Guard exist?
	"Allow Chill Guard" = true
	#Should Chill Guard be incompatible with Blaze Guard?
	"Incompatible with Blaze Guard" = true
	#Should Chill Guard be incompatible with Shove
	"Incompatible with Chill Guard" = true
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = true

[Sensing]
	#Should Sensing exist?
	"Allow Sensing" = false
	#Should Sensing be incompatible with Aqua Affinity?
	"Incompatible with Aqua Affinity" = true
	#Should Sensing be incompatible with Respiration?
	"Incompatible with Respiration" = false
	#Should this enchantment be found on the Enchanting Table?
	"Find on Enchanting Table" = false
	#Determines the way Sensing should act: whether it should grant night vision (true) or create light around the user (false)
	"Sensing Mode" = false

