# Use Cloth Config mod for the descriptions.
---
enable: true
transitionSpeed: 1.0
nimbleMounting: false
mountingEntityBlocklist: []
nimbleElytra: true
elytraRollScreen: true
elytraRollStrength: 20
elytraTickDelay: 10
frontKeyToggleMode: true
expectedThirdPersonDistance: 4.0
