
#    ═════════════════════════ Attention ═════════════════════════
#    Don't use this if you don't know what you are doing
#        REASON:
#    This file is a conditional registration. This is harmless in Singleplayer World,
#    but harmful in SERVER because you won't able to join.
#
#    ══════════════════════════ Detail ═══════════════════════════
#    This file allow you to exclude StoneTypes, MudType, EntrySet
#    1) You can find their names for StoneTypes, MudType, or EntrySet in `everycomp-entries.toml`
#    2) Leave a value empty to disable that rule.
#
#    Module - is a Supported Mod, just a modId is sufficient.
#    EntrySet - is a FurnitureType or DecorativeType that Stone-Zone is supporting via the mod. it is either block or item.
#
#    NOTE: blacklisting a Module will be applied to Wood-Good, Stone-Zone, Gems-Realm - if you want to blacklist, then use everycomp-hazardous.toml
#
[stonetype]
	#Exclude StoneType from all of Modules
	#    EXAMPLE: blacklist = [
	#        "forestry:.*fireproof.*",		COMMENT: .* is an RegEx, it exclude all of StoneType containing "fireproof" from Forestry
	#        "biomesoplenty:.*",				COMMENT: .* is an RegEx, it exclude all of StoneType from Wood Mod for any Module
	#        "biomesoplenty:redwood"		COMMENT: exclude redwood from Stone Mod for any module
	#    ]
	#
	blacklist = []

[mudtype]
	#Exclude MudType from all of Modules
	#	The example is same as StoneType's
	blacklist = []

[entryset]
	#Exclude EntrySet from the module for All of StoneType or MudType
	#    This is only applied to Stone-Zone.
	#    EXAMPLE: blacklist = [
	#        "chipped:checkered_trapdoor",	COMMENT: chipped:checkered_oak_trapdoor without "oak"
	#        "variantvanillablocks:chest",	COMMENT: variantvanillablocks:oak_chest without "oak"
	#        "chipped:.*"					COMMENT: .* is an regex which will exclude all of EntrySets from one Module
	#    ]
	#
	blacklist = []

